export type Region = "European" | "Asian" | "Middle Eastern" | "African" | "Americas & Pacific";

export interface Language {
  name: string;
  native: string;
  flag: string;
  region: Region;
  featured?: boolean;
}

export const REGIONS: Region[] = [
  "European",
  "Asian",
  "Middle Eastern",
  "African",
  "Americas & Pacific",
];

export const allLanguages: Language[] = [
  // ── European ──────────────────────────────────────────────────────────────
  { name: "English",      native: "English",       flag: "🇬🇧", region: "European", featured: true },
  { name: "Spanish",      native: "Español",        flag: "🇪🇸", region: "European", featured: true },
  { name: "French",       native: "Français",       flag: "🇫🇷", region: "European", featured: true },
  { name: "German",       native: "Deutsch",        flag: "🇩🇪", region: "European", featured: true },
  { name: "Italian",      native: "Italiano",       flag: "🇮🇹", region: "European", featured: true },
  { name: "Portuguese",   native: "Português",      flag: "🇵🇹", region: "European", featured: true },
  { name: "Russian",      native: "Русский",        flag: "🇷🇺", region: "European", featured: true },
  { name: "Turkish",      native: "Türkçe",         flag: "🇹🇷", region: "European", featured: true },
  { name: "Georgian",     native: "ქართული",       flag: "🇬🇪", region: "European", featured: true },
  { name: "Dutch",        native: "Nederlands",     flag: "🇳🇱", region: "European" },
  { name: "Swedish",      native: "Svenska",        flag: "🇸🇪", region: "European" },
  { name: "Norwegian",    native: "Norsk",          flag: "🇳🇴", region: "European" },
  { name: "Danish",       native: "Dansk",          flag: "🇩🇰", region: "European" },
  { name: "Finnish",      native: "Suomi",          flag: "🇫🇮", region: "European" },
  { name: "Polish",       native: "Polski",         flag: "🇵🇱", region: "European" },
  { name: "Czech",        native: "Čeština",        flag: "🇨🇿", region: "European" },
  { name: "Slovak",       native: "Slovenčina",     flag: "🇸🇰", region: "European" },
  { name: "Hungarian",    native: "Magyar",         flag: "🇭🇺", region: "European" },
  { name: "Romanian",     native: "Română",         flag: "🇷🇴", region: "European" },
  { name: "Bulgarian",    native: "Български",      flag: "🇧🇬", region: "European" },
  { name: "Croatian",     native: "Hrvatski",       flag: "🇭🇷", region: "European" },
  { name: "Serbian",      native: "Српски",         flag: "🇷🇸", region: "European" },
  { name: "Bosnian",      native: "Bosanski",       flag: "🇧🇦", region: "European" },
  { name: "Slovenian",    native: "Slovenščina",    flag: "🇸🇮", region: "European" },
  { name: "Macedonian",   native: "Македонски",     flag: "🇲🇰", region: "European" },
  { name: "Albanian",     native: "Shqip",          flag: "🇦🇱", region: "European" },
  { name: "Greek",        native: "Ελληνικά",       flag: "🇬🇷", region: "European" },
  { name: "Ukrainian",    native: "Українська",     flag: "🇺🇦", region: "European" },
  { name: "Belarusian",   native: "Беларуская",     flag: "🇧🇾", region: "European" },
  { name: "Lithuanian",   native: "Lietuvių",       flag: "🇱🇹", region: "European" },
  { name: "Latvian",      native: "Latviešu",       flag: "🇱🇻", region: "European" },
  { name: "Estonian",     native: "Eesti",          flag: "🇪🇪", region: "European" },
  { name: "Armenian",     native: "Հայերեն",        flag: "🇦🇲", region: "European" },
  { name: "Azerbaijani",  native: "Azərbaycan",     flag: "🇦🇿", region: "European" },
  { name: "Welsh",        native: "Cymraeg",        flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", region: "European" },
  { name: "Irish",        native: "Gaeilge",        flag: "🇮🇪", region: "European" },
  { name: "Scottish Gaelic", native: "Gàidhlig",   flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", region: "European" },
  { name: "Icelandic",    native: "Íslenska",       flag: "🇮🇸", region: "European" },
  { name: "Faroese",      native: "Føroyskt",       flag: "🇫🇴", region: "European" },
  { name: "Maltese",      native: "Malti",          flag: "🇲🇹", region: "European" },
  { name: "Catalan",      native: "Català",         flag: "🇦🇩", region: "European" },
  { name: "Basque",       native: "Euskara",        flag: "🇪🇸", region: "European" },
  { name: "Luxembourgish",native: "Lëtzebuergesch", flag: "🇱🇺", region: "European" },
  { name: "Breton",       native: "Brezhoneg",      flag: "🇫🇷", region: "European" },

  // ── Asian ─────────────────────────────────────────────────────────────────
  { name: "Japanese",     native: "日本語",          flag: "🇯🇵", region: "Asian", featured: true },
  { name: "Chinese (Mandarin)", native: "普通话",   flag: "🇨🇳", region: "Asian", featured: true },
  { name: "Korean",       native: "한국어",          flag: "🇰🇷", region: "Asian", featured: true },
  { name: "Hindi",        native: "हिन्दी",         flag: "🇮🇳", region: "Asian", featured: true },
  { name: "Chinese (Cantonese)", native: "粵語",    flag: "🇭🇰", region: "Asian" },
  { name: "Vietnamese",   native: "Tiếng Việt",     flag: "🇻🇳", region: "Asian" },
  { name: "Thai",         native: "ภาษาไทย",        flag: "🇹🇭", region: "Asian" },
  { name: "Indonesian",   native: "Bahasa Indonesia",flag: "🇮🇩", region: "Asian" },
  { name: "Malay",        native: "Bahasa Melayu",  flag: "🇲🇾", region: "Asian" },
  { name: "Filipino",     native: "Filipino",        flag: "🇵🇭", region: "Asian" },
  { name: "Bengali",      native: "বাংলা",           flag: "🇧🇩", region: "Asian" },
  { name: "Urdu",         native: "اردو",            flag: "🇵🇰", region: "Asian" },
  { name: "Tamil",        native: "தமிழ்",           flag: "🇱🇰", region: "Asian" },
  { name: "Telugu",       native: "తెలుగు",          flag: "🇮🇳", region: "Asian" },
  { name: "Marathi",      native: "मराठी",           flag: "🇮🇳", region: "Asian" },
  { name: "Gujarati",     native: "ગુજરાતી",         flag: "🇮🇳", region: "Asian" },
  { name: "Punjabi",      native: "ਪੰਜਾਬੀ",          flag: "🇮🇳", region: "Asian" },
  { name: "Kannada",      native: "ಕನ್ನಡ",           flag: "🇮🇳", region: "Asian" },
  { name: "Burmese",      native: "မြန်မာဘာသာ",     flag: "🇲🇲", region: "Asian" },
  { name: "Khmer",        native: "ខ្មែរ",            flag: "🇰🇭", region: "Asian" },
  { name: "Lao",          native: "ພາສາລາວ",         flag: "🇱🇦", region: "Asian" },
  { name: "Mongolian",    native: "Монгол",          flag: "🇲🇳", region: "Asian" },
  { name: "Tibetan",      native: "བོད་སྐད།",         flag: "🏔️",  region: "Asian" },
  { name: "Nepali",       native: "नेपाली",          flag: "🇳🇵", region: "Asian" },
  { name: "Sinhalese",    native: "සිංහල",           flag: "🇱🇰", region: "Asian" },
  { name: "Uzbek",        native: "O'zbek",          flag: "🇺🇿", region: "Asian" },
  { name: "Kazakh",       native: "Қазақ",           flag: "🇰🇿", region: "Asian" },
  { name: "Kyrgyz",       native: "Кыргызча",        flag: "🇰🇬", region: "Asian" },
  { name: "Javanese",     native: "Basa Jawa",       flag: "🇮🇩", region: "Asian" },
  { name: "Sundanese",    native: "Basa Sunda",      flag: "🇮🇩", region: "Asian" },

  // ── Middle Eastern ────────────────────────────────────────────────────────
  { name: "Arabic",       native: "العربية",         flag: "🇸🇦", region: "Middle Eastern", featured: true },
  { name: "Hebrew",       native: "עברית",           flag: "🇮🇱", region: "Middle Eastern" },
  { name: "Persian",      native: "فارسی",           flag: "🇮🇷", region: "Middle Eastern" },
  { name: "Kurdish",      native: "Kurdî",           flag: "🌍",  region: "Middle Eastern" },
  { name: "Pashto",       native: "پښتو",            flag: "🇦🇫", region: "Middle Eastern" },
  { name: "Dari",         native: "دری",             flag: "🇦🇫", region: "Middle Eastern" },

  // ── African ───────────────────────────────────────────────────────────────
  { name: "Swahili",      native: "Kiswahili",       flag: "🇰🇪", region: "African" },
  { name: "Amharic",      native: "አማርኛ",            flag: "🇪🇹", region: "African" },
  { name: "Yoruba",       native: "Yorùbá",          flag: "🇳🇬", region: "African" },
  { name: "Igbo",         native: "Igbo",            flag: "🇳🇬", region: "African" },
  { name: "Hausa",        native: "Hausa",           flag: "🇳🇬", region: "African" },
  { name: "Zulu",         native: "isiZulu",         flag: "🇿🇦", region: "African" },
  { name: "Xhosa",        native: "isiXhosa",        flag: "🇿🇦", region: "African" },
  { name: "Afrikaans",    native: "Afrikaans",       flag: "🇿🇦", region: "African" },
  { name: "Somali",       native: "Soomaali",        flag: "🇸🇴", region: "African" },
  { name: "Malagasy",     native: "Malagasy",        flag: "🇲🇬", region: "African" },
  { name: "Wolof",        native: "Wolof",           flag: "🇸🇳", region: "African" },
  { name: "Twi",          native: "Twi",             flag: "🇬🇭", region: "African" },
  { name: "Lingala",      native: "Lingála",         flag: "🇨🇩", region: "African" },
  { name: "Tigrinya",     native: "ትግርኛ",            flag: "🇪🇷", region: "African" },

  // ── Americas & Pacific ────────────────────────────────────────────────────
  { name: "Quechua",      native: "Runasimi",        flag: "🇵🇪", region: "Americas & Pacific" },
  { name: "Nahuatl",      native: "Nāhuatl",         flag: "🇲🇽", region: "Americas & Pacific" },
  { name: "Guaraní",      native: "Avañe'ẽ",         flag: "🇵🇾", region: "Americas & Pacific" },
  { name: "Māori",        native: "Te Reo Māori",    flag: "🇳🇿", region: "Americas & Pacific" },
  { name: "Hawaiian",     native: "ʻŌlelo Hawaiʻi", flag: "🌺",  region: "Americas & Pacific" },
  { name: "Samoan",       native: "Gagana Samoa",    flag: "🇼🇸", region: "Americas & Pacific" },
];
